# Generated by Django 5.2.11 on 2026-02-14 08:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='docs_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='domain_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_overview',
            field=ckeditor.fields.RichTextField(blank=True, help_text='High-level system explanation', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='system_architecture',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Layer breakdown and data flow', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='trust_hardware_integrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='trust_live_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='trust_production_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='trust_real_world',
            field=models.BooleanField(default=False),
        ),
    ]
