# Generated by Django 5.2.11 on 2026-02-14 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
