# Generated by Django 5.2.11 on 2026-02-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_systemconnection_options_and_more'),
        ('projects', '0004_alter_project_full_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='category',
            name='scope_statement',
            field=models.TextField(blank=True, help_text='Scope statement (2-3 lines)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='system_node',
            field=models.ForeignKey(blank=True, help_text='Link to System Universe Node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.systemnode'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Short description (1 line)'),
        ),
    ]
