# Generated by Django 5.2.10 on 2026-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_technology_technologycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.CharField(choices=[('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Research', 'Research'), ('Production', 'Production')], default='Intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='deployment_status',
            field=models.CharField(choices=[('Prototype', 'Prototype'), ('Production', 'Production'), ('Research', 'Research'), ('Experimental', 'Experimental')], default='Prototype', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='system_layers',
            field=models.JSONField(blank=True, default=list, help_text="List of layers e.g. ['Hardware', 'Backend', 'AI', 'Application']"),
        ),
    ]
