# Generated by Django 5.2.10 on 2026-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_complexity_project_deployment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='system_layers',
            field=models.JSONField(blank=True, default=list, help_text="List of layers e.g. ['Hardware', 'Backend', 'AI', 'Application']", verbose_name='System Layers (JSON)'),
        ),
    ]
