# Generated by Django 5.2.10 on 2026-02-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_system_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome class e.g. 'fab fa-python'", max_length=50, null=True),
        ),
    ]
