# Generated by Django 5.2.11 on 2026-02-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Abishek M', max_length=100)),
                ('title', models.CharField(help_text='e.g., AI Engineer | ML Architect', max_length=200)),
                ('bio', models.TextField(help_text='Short bio for hero section')),
                ('detailed_bio', models.TextField(help_text='Longer bio for about section')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('logo', models.ImageField(blank=True, help_text='Site logo', null=True, upload_to='profile/')),
                ('resume', models.FileField(help_text='Upload updated PDF resume', upload_to='resume/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profile',
            },
        ),
    ]
