# Generated by Django 5.2.11 on 2026-02-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Command Center Profile', 'verbose_name_plural': 'Command Center Profile'},
        ),
        migrations.AddField(
            model_name='profile',
            name='current_building',
            field=models.CharField(blank=True, help_text='e.g. LLM-driven intelligent automation system', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='focus_areas',
            field=models.TextField(blank=True, help_text='GenAI architectures, LLM orchestration... (one per line)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='philosophy',
            field=models.CharField(default='Designing systems where intelligence meets the physical world.', help_text='Engineering Philosophy Line', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='detailed_bio',
            field=models.TextField(blank=True, help_text='Longer bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(help_text='e.g., Intelligent Systems & GenAI Engineer', max_length=200),
        ),
    ]
