# Generated by Django 5.2.11 on 2026-02-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_options_profile_current_building_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#00F5FF', help_text='Hex Color e.g. #00F5FF', max_length=50)),
                ('is_core', models.BooleanField(default=False, help_text='Is this the Central Intelligence Node?')),
                ('order_index', models.IntegerField(default=0, help_text='Order in orbit (0-12)')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Links to Project Category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.category')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('data', 'Data Flow'), ('inference', 'AI Inference'), ('feedback', 'Feedback Loop')], default='data', max_length=50)),
                ('strength', models.FloatField(default=1.0, help_text='Visual thickness/speed (0.1 - 2.0)')),
                ('is_bidirectional', models.BooleanField(default=False)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_out', to='core.systemnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_in', to='core.systemnode')),
            ],
        ),
    ]
