# Generated by Django 5.2.11 on 2026-02-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemnode_systemconnection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconnection',
            options={'verbose_name': 'System Connection', 'verbose_name_plural': 'System Connections'},
        ),
        migrations.AlterModelOptions(
            name='systemnode',
            options={'ordering': ['-is_core', 'order_index'], 'verbose_name': 'System Node', 'verbose_name_plural': 'System Nodes'},
        ),
        migrations.RemoveField(
            model_name='systemnode',
            name='active',
        ),
        migrations.AddField(
            model_name='systemnode',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional visual icon', null=True, upload_to='system_icons/'),
        ),
        migrations.AddField(
            model_name='systemnode',
            name='importance_weight',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='Controls node size/prominence (1-5)'),
        ),
        migrations.AddField(
            model_name='systemnode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle visibility in frontend'),
        ),
        migrations.AddField(
            model_name='systemnode',
            name='pulse_enabled',
            field=models.BooleanField(default=True, help_text='Controls glow pulse animation'),
        ),
        migrations.AlterField(
            model_name='systemconnection',
            name='is_bidirectional',
            field=models.BooleanField(default=False, help_text='Two-way flow'),
        ),
        migrations.AlterField(
            model_name='systemconnection',
            name='strength',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='Flow intensity (1-5)'),
        ),
        migrations.AlterField(
            model_name='systemnode',
            name='color',
            field=models.CharField(default='#00F5FF', help_text='Hex Color e.g. #00F5FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='systemnode',
            name='description',
            field=models.TextField(blank=True, help_text='Tooltip content'),
        ),
        migrations.AlterField(
            model_name='systemnode',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Is this the Central Intelligence Node? Only one allowed.'),
        ),
        migrations.AlterField(
            model_name='systemnode',
            name='order_index',
            field=models.IntegerField(default=0, help_text='Orbit position order (0-12)'),
        ),
        migrations.AlterField(
            model_name='systemnode',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for routing', unique=True),
        ),
        migrations.AlterField(
            model_name='systemnode',
            name='title',
            field=models.CharField(help_text='Display name of the node', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='systemconnection',
            unique_together={('from_node', 'to_node')},
        ),
    ]
