# Generated by Django 5.2.11 on 2026-02-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_systemconnection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilitySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('strength_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CurrentFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Current Focus Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key for the setting (e.g., 'theme_color')", max_length=50, unique=True)),
                ('value', models.TextField(help_text='Value of the setting')),
                ('description', models.CharField(blank=True, help_text='Description of what this setting controls', max_length=255)),
                ('is_public', models.BooleanField(default=True, help_text='If false, this setting is for internal/admin use only')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('profile_title', models.CharField(max_length=150)),
                ('slogan', models.CharField(max_length=250)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('enable_avatar_mode', models.BooleanField(default=False)),
                ('explore_cta_text', models.CharField(blank=True, help_text='Text for the main CTA button', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Identity Core (Singleton)',
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LiveSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('highlight_tag', models.CharField(blank=True, help_text="e.g. 'v2.0 Beta'", max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Live System (Singleton)',
            },
        ),
    ]
