# Generated by Django 5.2.11 on 2026-02-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_capabilitysignal_currentfocus_globalsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_3d', models.BooleanField(default=True, help_text='Toggle System Universe 3D visualization')),
                ('animation_speed', models.FloatField(default=1.0, help_text='Speed multiplier (0.5 - 2.0)')),
                ('max_nodes_limit', models.IntegerField(default=8, help_text='Max nodes to display in 3D view')),
                ('primary_color', models.CharField(default='#00E5FF', help_text='Main accent color (Hex)', max_length=7)),
                ('accent_color', models.CharField(default='#7C3AED', help_text='Secondary accent color (Hex)', max_length=7)),
                ('background_style', models.CharField(choices=[('dark', 'Dark'), ('gradient', 'Gradient'), ('minimal', 'Minimal')], default='dark', max_length=50)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configuration (Singleton)',
            },
        ),
    ]
