# Generated by Django 5.2.10 on 2026-02-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_globalconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitycore',
            name='degree',
            field=models.CharField(blank=True, help_text='e.g. B.Tech in Computer Science', max_length=100, null=True),
        ),
    ]
