# Generated by Django 5.2.10 on 2026-02-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_identitycore_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capabilitysignal',
            name='strength_level',
            field=models.CharField(choices=[('core', 'Core Strength'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default='Medium', max_length=10),
        ),
    ]
