# Generated by Django 5.2.10 on 2026-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_capabilitysignal_strength_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesystem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='livesystem',
            name='highlight_tag',
            field=models.CharField(blank=True, help_text="e.g. 'v2.0 Beta' or 'Experimental'", max_length=50, null=True),
        ),
    ]
