# Generated by Django 5.2.10 on 2026-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livesystem_updated_at_alter_livesystem_highlight_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentfocus',
            name='icon',
            field=models.CharField(default='fas fa-bullseye', help_text="Font Awesome class (e.g. 'fas fa-code')", max_length=50),
        ),
        migrations.AlterField(
            model_name='currentfocus',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the focus area.'),
        ),
    ]
