# Generated by Django 5.2.10 on 2026-02-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_currentfocus_icon_alter_currentfocus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesystem',
            name='status_label',
            field=models.CharField(default='/// ACTIVE_EVOLUTION_PHASE', help_text="System status header (e.g. '/// CURRENT_BUILD_STATUS')", max_length=50),
        ),
    ]
