# Generated by Django 5.2.10 on 2026-02-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_livesystem_status_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitycore',
            name='current_status',
            field=models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('freelancer', 'Freelancer')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='identitycore',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Company Name or College Name', max_length=150, null=True),
        ),
    ]
