# Generated by Django 5.2.11 on 2026-02-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField()),
                ('category', models.CharField(help_text='e.g. Frontend, Backend, AI', max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='skills/')),
            ],
        ),
    ]
